manage.py: fix app.app_context() causing sqlalchemy.orm.exc.DetachedInstanceError
When having more than one request to sign the code fails when
looking for the 2nd db-record (see following console-log)
When not calling "with app.app_context()" in mail_certificate()
the code seems to work. At least signs 2 requests and sends out
the EMail to the user

------- console log ------------------------

1 out of 1 certificate requests certified, commit? [y/n]./
./freifunk_sam0815-void7.key
./readme.txt
./freifunk_sam0815-void7-tcp.ovpn
./freifunk_sam0815-void7-udp.ovpn
./freifunk_sam0815-void7.crt
./freifunk-ca.crt
enterd mail_certificate()
sent

Traceback (most recent call last):
  File "./ca-manage.py", line 127, in <module>
    manager.run()
  File "/var/www/ca.berlin.freifunk.net/env/lib/python3.4/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/var/www/ca.berlin.freifunk.net/env/lib/python3.4/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/var/www/ca.berlin.freifunk.net/env/lib/python3.4/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "./ca-manage.py", line 64, in process
    print(prompt.format(request.id, request.email))
  File "/var/www/ca.berlin.freifunk.net/env/lib/python3.4/site-packages/sqlalchemy/orm/attributes.py", line 237, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/var/www/ca.berlin.freifunk.net/env/lib/python3.4/site-packages/sqlalchemy/orm/attributes.py", line 573, in get
    value = state._load_expired(state, passive)
  File "/var/www/ca.berlin.freifunk.net/env/lib/python3.4/site-packages/sqlalchemy/orm/state.py", line 480, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "/var/www/ca.berlin.freifunk.net/env/lib/python3.4/site-packages/sqlalchemy/orm/loading.py", line 610, in load_scalar_attributes
    (state_str(state)))
sqlalchemy.orm.exc.DetachedInstanceError: Instance <Request at 0x7f4ff3a2fb00> is not bound to a Session; attribute refresh operation cannot proceed

---- manage.py -----

def mail_certificate(id, email):
    print("enterd mail_certificate()")
    with app.app_context():
        msg = Message(
                app.config['MAIL_SUBJECT'],
                sender=app.config['MAIL_FROM'],
                recipients=[email]
                )
        msg.body = render_template('mail.txt')
        certificate_path = "{}/freifunk_{}.tgz".format(
                app.config['DIRECTORY_CLIENTS'],
                id
                )
        with app.open_resource(certificate_path) as fp:
            msg.attach(
                    "freifunk_{}.tgz".format(id),
                    "application/gzip",
                    fp.read()
                    )
        mail.send(msg)
        print("sent")

@requests_subcommands.command
def process():
    "Process new certificate requests"
    for request in Request.query.filter(Request.generation_date == None).all():  # noqa
        prompt = "Do you want to generate a certificate for {}, {} ?"
-->        print(prompt.format(request.id, request.email))
        print("Type y to continue")
        confirm = input('>')
        if confirm in ['Y', 'y']:
            print('generating certificate')
            call([app.config['COMMAND_BUILD'], request.id, request.email])
            request.generation_date = datetime.date.today()
            db.session.commit()
            mail_certificate(request.id, request.email)
            print()
        else:
            print('skipping generation \n')